name: Build .NET Backend

on:
  push:
    branches:
      - main
      - 5-set-up-ci-pipeline-for-backend-project
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:  
  AZURE_CONTAINER_REGISTRY: semzeridevacrpoland  
  CONTAINER_APP_NAME: semzeri-dev-ca-poland  
  RESOURCE_GROUP: semzeri-dev-rg-poland  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push container image to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
          file: backend/src/Semzeri.API/Dockerfile
          context: backend

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} \
            --replace-env-vars \
              ASPNETCORE_ENVIRONMENT=Development \
              ConnectionStrings__DefaultConnection="${{ secrets.CONNECTION_STRING }}" \
              AdminData__Email="${{ secrets.ADMIN_EMAIL }}" \
              AdminData__Password="${{ secrets.ADMIN_PASSWORD }}"
